# Note: these should prob be converted into enums

NON_CHATAF = dict(
    PATACH="ַ", KAMATZ="ָ", TZERE="ֵ", SEGOL="ֶ", CHIRIK="ִ", SHVA="ְ", SHURUK="ֻ", DAGESH="ּ", CHOLEM="ֹ"
)
CHATAF = dict(CHATAF_PATACH="ֲ", CHATAF_KAMATZ="ֳ", CHATAF_SEGOL="ֱ")

VAV = "ו"
YUD = "י"

COMPLEX = dict(
    SHURUK_VAV=VAV+NON_CHATAF["DAGESH"],
    CHOLEM_VAV=VAV+NON_CHATAF["CHOLEM"],
    CHIRIK_YUD=NON_CHATAF["CHIRIK"]+YUD,
    TZERE_YUD=NON_CHATAF["TZERE"]+YUD
)

NIKKUD = dict(**NON_CHATAF, **CHATAF, **COMPLEX)


EQUIVALLENCIES = {
    COMPLEX["CHOLEM_VAV"]: NON_CHATAF["CHOLEM"],
    COMPLEX["SHURUK_VAV"]: NON_CHATAF["SHURUK"],
    COMPLEX["CHIRIK_YUD"]: NON_CHATAF["CHIRIK"],
    COMPLEX["CHIRIK_YUD"]: NON_CHATAF["CHIRIK"],
    COMPLEX["TZERE_YUD"]: NON_CHATAF["TZERE"],
    CHATAF["CHATAF_SEGOL"]: NON_CHATAF["SEGOL"],
    CHATAF["CHATAF_KAMATZ"]: NON_CHATAF["CHOLEM"],
    CHATAF["CHATAF_PATACH"]: NON_CHATAF["PATACH"],
    
    NON_CHATAF["CHOLEM"]: COMPLEX["CHOLEM_VAV"],
    NON_CHATAF["SHURUK"]: COMPLEX["SHURUK_VAV"],
    NON_CHATAF["CHIRIK"]: COMPLEX["CHIRIK_YUD"],
    NON_CHATAF["TZERE"]: COMPLEX["TZERE_YUD"],
    NON_CHATAF["SEGOL"]: CHATAF["CHATAF_SEGOL"],
    NON_CHATAF["CHOLEM"]: CHATAF["CHATAF_KAMATZ"],
    NON_CHATAF["PATACH"]: CHATAF["CHATAF_PATACH"]
}

